[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Louis Stagg <louis.stagg717@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.23.*"
clap="3.0.0-beta.2"
pbr="1.0.*"
